### ISSUE TITLE
ignore option is always appended to a default list

### ISSUE THREAD

**Issue by atoomic** [sixapart/Mojolicious-Plugin-ClientIP#2]
The documentation do not list the default values always added to the `ignore` list,
but the main issue is to not be able to overwrite the default list.

For example, if you want to use it on an internal network and want to know who is accessing the app... I would like to be able to remove `10.0.0.0/8` from the default ignore list..

**Comment by usualoma** [comment]
Fixed in [0.02](https://metacpan.org/pod/release/SIXAPART/Mojolicious-Plugin-ClientIP-0.02/lib/Mojolicious/Plugin/ClientIP.pm)

We can use "private" option.
