### ISSUE TITLE
ignore list is shared among multiple apps

### ISSUE THREAD

**Issue by atoomic** [sixapart/Mojolicious-Plugin-ClientIP#4]
If you have two mojo apps running, the `sub _find` is going to be shared and as it's using a static variable for the ignore list, the two apps cannot have different ignore rules

suggestion remove the `state $ignore` in the find

**Comment by usualoma** [comment]
Fixed in [0.02](https://metacpan.org/pod/release/SIXAPART/Mojolicious-Plugin-ClientIP-0.02/lib/Mojolicious/Plugin/ClientIP.pm)
